language: node_js
node_js:
- '11'
dist: trusty
cache: 
  directories:
    - node_modules
    - .firebase
branches:
  only:
  - master
install:
  - npm install
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run build
before_deploy: "echo 'Deploying build to Firebase Hosting...'"
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "YsQMXaOixsz+q73PgcLQBWcYBppfMKM1Z2vfJjgXlcpgDwrKUODjv3T0BEl0KJm+OUeePXqc6bN9ySsWU3DmdlWwAnYCGP6jZvT61fDSRQ7F0rMAV5nCwku3zyVtVU2CUwyZ4Vu4+DXGoNp2Wvq11OZx1xqFk8bqho8M2B97m9fPvh9g5sm6wbWpr/T02iAd6XzNi1CvpwmAIW45hCznOScDxxeXUZg5hF+r/TlOGQRdTrDuc3Cv41cNW51S/8jXqFH5V56GdHnYhDDhDhQbXJPF/vXJBKyJS/e1qeugHH/bwGs+rVVNm8sXECFNDFVLMlX6BkWAgYJWgQBtEDb9KlsjfuAwLni/L19uIzDJ2YW7yjvVGGTW9LsGQ4yOvcLsilFIjLqboA5M3YW8qHn6W1x1QjqlAohZsIaTkR3CbMGDemS2QED7tS/wHALysEgtpWJ5uyWRwbtF25+oZCuem8yIdTL17und5ORtGJwwIgSRDQHoBu5WfgVulvzY+nWgygXwomwQLbzTGjSXZYkQ5O/dA3x22p9AYII8qmeaAG66DPzHypILHQFZQ57wiEkjgw04nzaWqXihkGEDR0cg8l7xWf7NyZquOROtx5/JRlAMWetNDLRyOeScEN1lCI9btqMTnx86Af8s0ZULpyU+N9aRgx8n6XmDox+OYrsCsms="
  message: "Deploy from Travis CI"